export const unitData = [
  {
    serial: "J317",
    company: "Polytrade",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J317.jpg").default,
  },
  {
    serial: "J319-1",
    company: "Roundhill",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J319.jpg").default,
  },
  {
    serial: "J319-2",
    company: "Roundhill",
    drive: "direct drive",
    type: "cooler",
    image: require("../src/unit-imgs/J319-2.jpg").default,
  },
  {
    serial: "J320",
    company: "ABPC",
    drive: "sub resonant",
    type: "screen",
    image: require("../src/unit-imgs/J320.jpg").default,
  },
  {
    serial: "J321",
    company: "ABPC",
    drive: "direct drive",
    type: "conveyor",
    image: require("../src/unit-imgs/J321.jpg").default,
  },
  {
    serial: "J322-1",
    company: "RDT",
    drive: "direct drive",
    type: "blower",
    image: require("../src/unit-imgs/J322-1.jpg").default,
  },
  {
    serial: "J322-2",
    company: "RDT",
    drive: "sub resonant",
    type: "screen",
    image: require("../src/unit-imgs/J322-2.jpg").default,
  },
  {
    serial: "J322-3",
    company: "RDT",
    drive: "sub resonant",
    type: "screen",
    image: require("../src/unit-imgs/J322-3.jpg").default,
  },
  {
    serial: "J323-1",
    company: "SIMS",
    drive: "sub resonant",
    type: "feeder",
    image: require("../src/unit-imgs/J323-1.jpg").default,
  },
  {
    serial: "J323-2",
    company: "SIMS",
    drive: "sub resonant",
    type: "screen",
    image: require("../src/unit-imgs/J323-2.jpg").default,
  },
  {
    serial: "J324",
    company: "JDM",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J324.jpg").default,
  },
  {
    serial: "J325",
    company: "Wastech",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J325.jpg").default,
  },
  {
    serial: "J326",
    company: "ABPC",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J326.jpg").default,
  },
  {
    serial: "J327",
    company: "RDT",
    drive: "direct drive",
    type: "conveyor",
    image: require("../src/unit-imgs/J327.jpg").default,
  },
  {
    serial: "J328",
    company: "Patties",
    drive: "direct drive",
    type: "conveyor",
    image: require("../src/unit-imgs/J328.jpg").default,
  },
  {
    serial: "J329-1",
    company: "Regain",
    drive: "sub resonant",
    type: "feeder",
    image: require("../src/unit-imgs/J329-1.jpg").default,
  },
  {
    serial: "J329-2",
    company: "Regain",
    drive: "sub resonant",
    type: "screen",
    image: require("../src/unit-imgs/J329-2.jpg").default,
  },
  {
    serial: "J329-3",
    company: "Regain",
    drive: "sub resonant",
    type: "conveyor",
    image: require("../src/unit-imgs/J329-3.jpg").default,
  },
  {
    serial: "J329-4",
    company: "Regain",
    drive: "sub resonant",
    type: "feeder",
    image: require("../src/unit-imgs/J329-4.jpg").default,
  },
  {
    serial: "J330",
    company: "Demast",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J330.jpg").default,
  },
  {
    serial: "J334",
    company: "Polytrade",
    drive: "direct drive",
    type: "screen",
    image: require("../src/unit-imgs/J334.jpg").default,
  },
];
export default unitData;
