const unitData = [
  {
    serial: "J317",
    company: "Polytrade",
    drive: "direct drive",
    type: "screen",
    image: "https://i.imgur.com/pXqu49p.jpg",
    profileImages: [
      "https://i.imgur.com/6ySI7DM.jpg",
      "https://i.imgur.com/Tskq91Y.jpg",
      "https://i.imgur.com/KlECt1W.jpg",
    ],

    supportFrame: "with",
    covers: "without",
    screeningMedia: "none",
    liners: "poly",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J319-1",
    company: "Roundhill",
    drive: "direct drive",
    type: "screen",
    image: "https://i.imgur.com/Vz3dlcy.jpg",
    profileImages: [
      "https://i.imgur.com/Vz3dlcy.jpg",
      "https://i.imgur.com/AqrKVSX.jpg",
      "https://i.imgur.com/TYoeUCv.jpg",
      "https://i.imgur.com/5kCsgfD.jpg",
    ],
    supportFrame: "with",
    covers: "with",
    screeningMedia: "mesh",
    liners: "none",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J319-2",
    company: "Roundhill",
    drive: "direct drive",
    type: "cooler",
    image: "https://i.imgur.com/jBsPs28.jpg",
    profileImages: [
      "https://i.imgur.com/1oEjR84.jpg",
      "https://i.imgur.com/jBsPs28.jpg",
      "https://i.imgur.com/TUqJpvy.jpg",
    ],
    supportFrame: "with",
    covers: "with",
    screeningMedia: "none",
    liners: "none",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J320",
    company: "ABPC",
    drive: "sub resonant",
    type: "screen",
    image: "https://imgur.com/jUx93Pd.jpg",
    profileImages: [
      "https://imgur.com/jUx93Pd.jpg",
      "https://imgur.com/TzWfJaB.jpg",
      "https://imgur.com/RJFErOC.jpg",
      "https://imgur.com/LiRRLTX.jpg",
      "https://imgur.com/m4gT9nM.jpg",
      "https://imgur.com/nBmijuC.jpg",
      "https://imgur.com/8603NsK.jpg",
    ],
    supportFrame: "with",
    covers: "with",
    screeningMedia: "poly mat",
    liners: "poly",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J321",
    company: "ABPC",
    drive: "direct drive",
    type: "conveyor",
    image: "https://i.imgur.com/EyUH9a3.jpg",
    profileImages: [
      "https://i.imgur.com/EyUH9a3.jpg",
      "https://i.imgur.com/TaKSruY.jpg",
      "https://i.imgur.com/5mVcbVa.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "none",
    liners: "ceramic",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J322-1",
    company: "RDT",
    drive: "direct drive",
    type: "blower",
    image: "https://i.imgur.com/4kTaM1Z.jpg",
    profileImages: [
      "https://i.imgur.com/4kTaM1Z.jpg",
      "https://i.imgur.com/jGtUpMq.jpg",
      "https://i.imgur.com/jGtUpMq.jpg",
    ],
    supportFrame: "without",
    covers: "with",
    screeningMedia: "mesh",
    liners: "poly",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J322-2",
    company: "RDT",
    drive: "sub resonant",
    type: "flip flow",
    image: "https://i.imgur.com/9NnKmnP.jpg",
    profileImages: [
      "https://i.imgur.com/9NnKmnP.jpg",
      "https://i.imgur.com/6gZLmSR.jpg",
      "https://i.imgur.com/sxs2ex7.jpg",
      "https://i.imgur.com/xaJmjv6.jpg",
      "https://i.imgur.com/wHMaoEJ.jpg",
      "https://i.imgur.com/6xQg8kq.jpg",
    ],
    supportFrame: "without",
    covers: "with",
    screeningMedia: "poly mat",
    liners: "poly",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J322-3",
    company: "RDT",
    drive: "sub resonant",
    type: "flip flow",
    image: "https://i.imgur.com/XYrZsGl.jpg",
    profileImages: [
      "https://i.imgur.com/XYrZsGl.jpg",
      "https://i.imgur.com/sPSxn8a.jpg",
      "https://i.imgur.com/9V8VpeZ.jpg",
    ],
    supportFrame: "without",
    covers: "with",
    screeningMedia: "poly mat",
    liners: "poly",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J323-1",
    company: "SIMS",
    drive: "sub resonant",
    type: "feeder",
    image: "https://i.imgur.com/em1emV3.jpg",
    profileImages: [
      "https://i.imgur.com/em1emV3.jpg",
      "https://i.imgur.com/sBk9ZQG.jpg",
      "https://i.imgur.com/PUy6M9E.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "none",
    liners: "bisalloy",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J323-2",
    company: "SIMS",
    drive: "sub resonant",
    type: "screen",
    image: "https://i.imgur.com/yRXSXGC.jpg",
    profileImages: [
      "https://i.imgur.com/yRXSXGC.jpg",
      "https://i.imgur.com/BV4pPDj.jpg",
      "https://i.imgur.com/M1OfMDv.jpg",
      "https://i.imgur.com/vwzg2W6.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "finger",
    liners: "bisalloy",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J324",
    company: "JDM",
    drive: "direct drive",
    type: "screen",
    image: "https://i.imgur.com/Jy2RdNB.jpg",
    profileImages: [
      "https://i.imgur.com/Jy2RdNB.jpg",
      "https://i.imgur.com/dpTBMXz.jpg",
      "https://i.imgur.com/jJioNwg.jpg",
      "https://i.imgur.com/7l4QSDm.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "perforated plate",
    liners: "none",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J325",
    company: "Wastech",
    drive: "direct drive",
    type: "screen",
    image: "https://i.imgur.com/iilxfDK.jpg",
    profileImages: [
      "https://i.imgur.com/iilxfDK.jpg",
      "https://i.imgur.com/liZ9ug0.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "finger",
    liners: "none",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J326",
    company: "ABPC",
    drive: "direct drive",
    type: "screen",
    image: "https://i.imgur.com/rxDMPBB.jpg",
    profileImages: ["https://i.imgur.com/rxDMPBB.jpg"],
    supportFrame: "without",
    covers: "without",
    screeningMedia: "poly panel",
    liners: "poly",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J327",
    company: "RDT",
    drive: "direct drive",
    type: "conveyor",
    image: "https://i.imgur.com/7SNN5o1.jpg",
    profileImages: [
      "https://i.imgur.com/7SNN5o1.jpg",
      "https://i.imgur.com/EYHGaJj.jpg",
    ],

    supportFrame: "without",
    covers: "without",
    screeningMedia: "none",
    liners: "poly",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J328",
    company: "Patties",
    drive: "direct drive",
    type: "conveyor",
    image: "https://i.imgur.com/TsRAmRC.jpg",
    profileImages: [
      "https://i.imgur.com/TsRAmRC.jpg",
      "https://i.imgur.com/NydUtsV.jpg",
      "https://i.imgur.com/1nkaXcu.jpg",
      "https://i.imgur.com/bpNvTot.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "none",
    liners: "none",
    supports: "oscillating mounts",
    materialConstruction: "SS",
  },
  {
    serial: "J329-1",
    company: "Regain",
    drive: "sub resonant",
    type: "feeder",
    image: "https://i.imgur.com/9odNUby.jpg",
    profileImages: [
      "https://i.imgur.com/9odNUby.jpg",
      "https://i.imgur.com/9VCinG8.jpg",
      "https://i.imgur.com/GgFRXM7.jpg",
      "https://i.imgur.com/vYRvWRq.jpg",
    ],
    supportFrame: "without",
    covers: "without",
    screeningMedia: "none",
    liners: "bisalloy",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J329-2",
    company: "Regain",
    drive: "sub resonant",
    type: "screen",
    image: "https://i.imgur.com/G6TGuJP.jpg",
    profileImages: [
      "https://i.imgur.com/G6TGuJP.jpg",
      "https://i.imgur.com/VF3iUGf.jpg",
      "https://i.imgur.com/Uv7N7Qv.jpg",
    ],
    supportFrame: "without",
    covers: "without",
    screeningMedia: "perforated plate",
    liners: "bisalloy",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J329-3",
    company: "Regain",
    drive: "sub resonant",
    type: "conveyor",
    image: "https://i.imgur.com/Ce3hBeV.jpg",
    profileImages: [
      "https://i.imgur.com/Ce3hBeV.jpg",
      "https://i.imgur.com/aOmvlrX.jpg",
      "https://i.imgur.com/Db8ZDno.jpg",
    ],
    supportFrame: "without",
    covers: "without",
    screeningMedia: "none",
    liners: "bisalloy",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J329-4",
    company: "Regain",
    drive: "sub resonant",
    type: "feeder",
    image: "https://i.imgur.com/5hXoUd0.jpg",
    profileImages: [
      "https://i.imgur.com/5hXoUd0.jpg",
      "https://i.imgur.com/O0mAgFP.jpg",
      "https://i.imgur.com/ffU3ND6.jpg",
      "https://i.imgur.com/mTK3s3P.jpg",
    ],
    supportFrame: "without",
    covers: "with",
    screeningMedia: "none",
    liners: "bisalloy",
    supports: "oscillating mounts",
    materialConstruction: "MS G250",
  },
  {
    serial: "J330",
    company: "Demast",
    drive: "direct drive",
    type: "screen",
    image: "https://i.imgur.com/YFgnCXg.jpg",
    profileImages: [
      "https://i.imgur.com/YFgnCXg.jpg",
      "https://i.imgur.com/v7LAt7A.jpg",
      "https://i.imgur.com/APboL1q.jpg",
    ],
    supportFrame: "without",
    covers: "without",
    screeningMedia: "poly panel",
    liners: "poly",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
  {
    serial: "J334",
    company: "Polytrade",
    drive: "sub resonant",
    type: "screen",
    image: "https://i.imgur.com/gsJ5NOC.jpg",
    profileImages: [
      "https://i.imgur.com/gsJ5NOC.jpg",
      "https://i.imgur.com/AZZPqYP.jpg",
      "https://i.imgur.com/nnFYQxm.jpg",
    ],
    supportFrame: "with",
    covers: "without",
    screeningMedia: "finger",
    liners: "poly",
    supports: "steel coils",
    materialConstruction: "MS G250",
  },
];
export default unitData;
